export const ERROR_CODES = {
  UNAUTHORIZED: 'AUTH_001',
  FORBIDDEN: 'AUTH_002',
  INVALID_CREDENTIALS: 'AUTH_003',
  OTP_INVALID_OR_EXPIRED: 'AUTH_004',
  OTP_MAX_ATTEMPTS: 'AUTH_005',
  TOKEN_EXPIRED: 'AUTH_006',

  RESOURCE_NOT_FOUND: 'RES_001',
  RESOURCE_ALREADY_EXISTS: 'RES_002',
  VALIDATION_ERROR: 'VAL_001',
  INTERNAL_SERVER_ERROR: 'SYS_001',
  IMPORT_FAILED: 'IMP_001',
  FILE_UPLOAD_ERROR: 'DOC_001',
} as const;
